import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';
import './globals.css';
import 'beta-parity-react/ui/theme/index.css';
import SideBar from '@components/doc/SideBar';
import ThemeProvider from '@components/doc/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Demo | React Components Library',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme') as any;
  const isValidTheme = theme ? ['light', 'dark'].includes(theme.value) : false;

  return (
    <html lang='en'>
      <ThemeProvider initialTheme={isValidTheme ? theme.value : 'light'}>
        <SideBar />
        <main className='prose flex min-h-screen flex-1 flex-col gap-8 overflow-hidden p-8 sm:px-12 md:px-24 2xl:px-48'>
          {children}
        </main>
      </ThemeProvider>
    </html>
  );
}
