export const styleMap = {
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  mx: 'marginX',
  my: 'marginY',

  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  px: 'paddingX',
  py: 'paddingY',

  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
  maxW: 'maxWidth',
  maxH: 'maxHeight',

  bg: 'backgroundColor',
  cl: 'color',
  op: 'opacity',

  bd: 'border',
  bdColor: 'borderColor',
  bdWidth: 'borderWidth',
  bdStyle: 'borderStyle',
  radius: 'borderRadius',

  position: 'position',
  t: 'top',
  r: 'right',
  b: 'bottom',
  l: 'left',
  z: 'zIndex',
  in: 'inset',

  display: 'display',

  flex: 'flex',
  flexGrow: 'flexGrow',
  flexShrink: 'flexShrink',
  flexBasis: 'flexBasis',
  flexDir: 'flexDirection',
  flexDirection: 'flexDirection',
  flexWrap: 'flexWrap',
  justifyContent: 'justifyContent',
  alignItems: 'alignItems',
  alignContent: 'alignContent',

  grid: 'grid',
  gridColumn: 'gridColumn',
  gridRow: 'gridRow',
  gridAutoFlow: 'gridAutoFlow',
  gridAutoColumns: 'gridAutoColumns',
  gridAutoRows: 'gridAutoRows',
  gridTemplateColumns: 'gridTemplateColumns',
  gridTemplateRows: 'gridTemplateRows',
  gridTemplateAreas: 'gridTemplateAreas',
  gridArea: 'gridArea',
  gridGap: 'gridGap',
  gridRowGap: 'gridRowGap',
  gridColumnGap: 'gridColumnGap',
  gridRowStart: 'gridRowStart',
  gridRowEnd: 'gridRowEnd',
  gridColumnStart: 'gridColumnStart',
  gridColumnEnd: 'gridColumnEnd'
} as const;
